name: Test Runner
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Environment
        run: |
          hostname
          uname -a
          docker version
          docker ps
