name: Test Runner
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check Environment
        run: |
          hostname
          uname -a
          docker version
          docker ps
          echo "SONAR_HOST_URL=${SONAR_HOST_URL}"
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      
      - name: Build image
        run: |
          docker build -t harbor.azhuan.ren/sre_uat/xbb-nginx:${GITHUB_SHA::7} .

      - name: Push image
        run: |
          docker push harbor.azhuan.ren/sre_uat/xbb-nginx:${GITHUB_SHA::7}
      
      - name: Deploy k3s
        run: |
          echo "本次更新镜像harbor.azhuan.ren/sre_uat/xbb-nginx":"${GITHUB_SHA::7}"
          docker run --rm \
            -e KUBECONFIG=/root/.kube/config \
            -v /root/.kube/config:/root/.kube/config \
            bitnami/kubectl:latest \
            set image deployment/xbb-nginx-v5 \
            nginx=harbor.azhuan.ren/sre_uat/xbb-nginx:"${GITHUB_SHA::7}"
